40

In [4]:
import pandas as pd

In [5]:
df = pd.read_excel("coffee (1).xlsx")
df.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   datetime64[us]
 1   datetime     3636 non-null   datetime64[us]
 2   cash_type    3636 non-null   str
 3   card         3547 non-null   str
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   str
dtypes: datetime64[us](2), float64(1), str(3)
memory usage: 170.6 KB

In [9]:
df["year"] = df["date"].dt.year
df.head()

,date,datetime,cash_type,card,money,coffee_name,year
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,2024
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,2024
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,2024

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [19]:
df["year"] = df["date"].dt.year
df.head()

,date,datetime,cash_type,card,money,coffee_name,year,month,month_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,2024,2024,<bound method DatetimeArray.month_name of <pan...
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,2024,<bound method DatetimeArray.month_name of <pan...
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,2024,<bound method DatetimeArray.month_name of <pan...
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,2024,2024,<bound method DatetimeArray.month_name of <pan...
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,2024,2024,<bound method DatetimeArray.month_name of <pan...

In [20]:
df["day_name"] = df["date"].dt.day_name()
df.head()

,date,datetime,cash_type,card,money,coffee_name,year,month,month_name,day_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday

In [22]:
def time_check(time):
    if time.hour < 12:
        return "Morning"
    elif time.hour < 16:
        return "Afternoon"
    else:
        return "Evening"

In [23]:
df["time_of_day"] = df["datetime"].apply(time_check)
df.head()

,date,datetime,cash_type,card,money,coffee_name,year,month,month_name,day_name,time_of_day
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday,Morning
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday,Afternoon
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday,Afternoon
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday,Afternoon
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,2024,2024,<bound method DatetimeArray.month_name of <pan...,Friday,Afternoon

In [ ]:
# HOW TO DROP?SELECT COLUMNS
# TO SELECT MULTIPLE COLUMNS
df = df[["month", "year", "day"]]
df.head()

In [ ]:
# TO DROP COLUMNS YOU DON'T WANT
df = df.drop(["date", "datetime", "card"], axis=1)
df.head()

In [ ]:
# TO RENAME A COLUMN
df.rename